baseurl = "https://nashgo.org/"
languageCode = "en-us"
title = "Nashville Gophers"
# Enable comments by entering your Disqus shortname
disqusShortname = "nashgo"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-87328927-1"
# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "â†©"
theme = "hugo-icarus-theme"


[permalinks]
    post = "/:year/:month/:day/:slug"


[params]
    # Tell me who you are
    author = "Nashville Gophers"
    bio = "Friends - Developers - Humans"
    location = "Nashville, TN"
    site_description = "A place where people can meet and talking about developing with Go"
    copyright  = "The Nashville Gophers"
    avatar = "css/images/gopherbw.png"
    logo = "css/images/go-gopher3.png"

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

    # Add custom assets with their paths relative to the static folder
	custom_css = []
	custom_js  = []

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

[[params.menu]]
    before = false
    label  = "Tags"
    link   = "tags/"

[[params.menu]]
    before = false
    label  = "Categories"
    link   = "categories/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://github.com/nashgo"


[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "nashgo"
    twitter         = "nashgophers"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true
